version: "3.7"
services:
  backend:
    image: todo-backend:v2
    ports:
      - 4000:4000
    command: >
      /bin/sh -c "
        while ! nc -z mongodb 27017 ; do
          echo 'Waiting for mongodb service to be up and running';
          sleep 1
        done
        node server.js;
        "

  mongodb:
    image: mongo
    expose:
      - 27017
